/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: PosMsg.h
  Source: C:\Users\Alcomarxism\Documents\QtProject\turtle_follower_dds\PosMsg.idl
  Cyclone DDS: V11.0.1

*****************************************************************/
#ifndef DDSC_POSMSG_H_531BC66B1BF4045F47A8FA6D6266F942
#define DDSC_POSMSG_H_531BC66B1BF4045F47A8FA6D6266F942

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PosMsg
{
  float x;
  float y;
  float theta;
} PosMsg;

extern const dds_topic_descriptor_t PosMsg_desc;

#define PosMsg__alloc() \
((PosMsg*) dds_alloc (sizeof (PosMsg)));

#define PosMsg_free(d,o) \
dds_sample_free ((d), &PosMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_POSMSG_H_531BC66B1BF4045F47A8FA6D6266F942 */
