/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: TeleopMsg.h
  Source: C:\Users\Alcomarxism\Documents\QtProject\turtle_follower_dds\TeleopMsg.idl
  Cyclone DDS: V11.0.1

*****************************************************************/
#ifndef DDSC_TELEOPMSG_H_49AF7948003014590E3AB92DBD87EB13
#define DDSC_TELEOPMSG_H_49AF7948003014590E3AB92DBD87EB13

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct TeleopMsg
{
  float speed;
  float angSpeed;
} TeleopMsg;

extern const dds_topic_descriptor_t TeleopMsg_desc;

#define TeleopMsg__alloc() \
((TeleopMsg*) dds_alloc (sizeof (TeleopMsg)));

#define TeleopMsg_free(d,o) \
dds_sample_free ((d), &TeleopMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TELEOPMSG_H_49AF7948003014590E3AB92DBD87EB13 */
